### ISSUE TITLE
七牛官方框架问题提示（Android）

### ISSUE THREAD

**Issue by besthyhy** [GuiminChu/flutter_qiniu#1]
七牛从7.3.13起移除了 happy-dns，而本插件使用的依赖方式为：implementation 'com.qiniu:qiniu-android-sdk:7.3.+' , 这个 "+" 会让所依赖的框架升级到最新。android8 会闪退。

我目前通过将框架版本写死，来解决这个问题：implementation 'com.qiniu:qiniu-android-sdk:7.3.12'

出现这个问题，不是本框架的失误，而是七牛开发者不够严谨，当版本不兼容时，应该改变大版本号或中版本号的，但是七牛开发者没改。

参考：https://developer.qiniu.com/kodo/sdk/1236/android
推荐使用最新版，7.3.13 及以上版本。
从 7.3.13 开始，不在强制依赖 happy-dns-android，默认不再提供 httpDns，可以调用 Configuration.Builder#dns(com.qiniu.android.http.Dns)方法设置外部 Dns，自定义 Dns 要求实现 com.qiniu.android.http.Dns 接口。
如果可以明确 区域 的话，最好指定固定区域，这样可以少一步网络请求，少一步出错的可能。

**Comment by besthyhy** [comment]
修正：闪退的是 android9 。

**Comment by GuiminChu** [comment]
感谢。0.1.2 暂时修改了七牛框架的版本号 com.qiniu:qiniu-android-sdk:7.3.12。
