### ISSUE TITLE
安卓上传的时候就会崩溃，这种怎么解决呢

### ISSUE THREAD

**Issue by qq329401134** [GuiminChu/flutter_qiniu#2]
报错信息
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: No static method immutableList(Ljava/util/List;)Ljava/util/List; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/com.example.younengapp-YCRIaI6uoorfhSuZ47Ap8g==/base.apk) @GuiminChu

**Comment by GuiminChu** [comment]
0.1.2 版本已修复。

**Comment by see-sea** [comment]
0.1.3还是崩溃
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: No static method immutableList(Ljava/util/List;)Ljava/util/List; in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/packagename-Im3TcdH9y6hgqpMmKOYnLA==/base.apk!classes3.dex)

**Comment by aluo44** [comment]
解决办法
在作者的插件的android文件夹里build.gradle里指定一下七牛版本就解决了. implementation 'com.qiniu:giniu-android-sdk.7.3.12"
